# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ac1ef866feff49e181139b2473429fe6a203e366714df4b38a65ef8b203e2b50577aa5c1e525dd07747b32f6a89bae669d23785f51a2eee2da75d1a211f283c

test:
  secret_key_base: 2513f8c869f12b18f71f3b445fe08a7cd755729dab838f63f756619fdc9a7039964999221417a437faed76aa6245df713299c6d61bb67bc9c99fd0e0418b8cf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
